// .gitignore rules for frameworks and platforms. Tool-specific.
// Content is hand-written based on well-known github/gitignore patterns,
// kept accurate but concise (not the full upstream lists).

import type { GitignoreTemplate } from './types';

export const FRAMEWORK_TEMPLATES: readonly GitignoreTemplate[] = [
  {
    id: 'react-vite',
    name: 'React/Vite',
    category: 'Frameworks',
    rules: ['dist/', 'dist-ssr/', '*.local', '.vite/', 'vite.config.*.timestamp-*'],
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'Frameworks',
    rules: ['.next/', 'out/', 'next-env.d.ts', '.vercel/'],
  },
  {
    id: 'nuxt',
    name: 'Nuxt',
    category: 'Frameworks',
    rules: ['.nuxt/', '.output/', '.nitro/', '.cache/', 'dist/'],
  },
  {
    id: 'angular',
    name: 'Angular',
    category: 'Frameworks',
    rules: ['/dist', '/tmp', '/out-tsc', '/bazel-out', '.angular/cache'],
  },
  {
    id: 'django',
    name: 'Django',
    category: 'Frameworks',
    rules: [
      '*.pyc',
      '__pycache__/',
      'db.sqlite3',
      'db.sqlite3-journal',
      '/media',
      '/staticfiles',
      'local_settings.py',
    ],
  },
  {
    id: 'laravel',
    name: 'Laravel',
    category: 'Frameworks',
    rules: [
      '/vendor',
      '/node_modules',
      '/public/hot',
      '/public/storage',
      '/storage/*.key',
      '/storage/framework/cache',
      '/storage/framework/sessions',
      '/storage/framework/views',
      '/bootstrap/cache',
      '.env',
      '.env.backup',
      '.phpunit.result.cache',
    ],
  },
  {
    id: 'rails',
    name: 'Rails',
    category: 'Frameworks',
    rules: [
      '/log/*',
      '/tmp/*',
      '/db/*.sqlite3',
      '/db/*.sqlite3-journal',
      '/public/system',
      '/public/assets',
      '/storage/*',
      '.byebug_history',
      '/config/master.key',
      '/config/credentials/*.key',
    ],
  },
  {
    id: 'spring-boot',
    name: 'Spring Boot',
    category: 'Frameworks',
    rules: [
      'target/',
      '!.mvn/wrapper/maven-wrapper.jar',
      '!**/src/main/**/target/',
      '!**/src/test/**/target/',
      '.mvn/timing.properties',
      '.mvn/wrapper/maven-wrapper.properties',
      'HELP.md',
    ],
  },
  {
    id: 'unity',
    name: 'Unity',
    category: 'Frameworks',
    rules: [
      '[Ll]ibrary/',
      '[Tt]emp/',
      '[Oo]bj/',
      '[Bb]uild/',
      '[Bb]uilds/',
      '[Ll]ogs/',
      '[Uu]serSettings/',
      '[Mm]emoryCaptures/',
      '*.csproj',
      '*.unityproj',
      '*.sln',
      '*.suo',
      '*.userprefs',
      'crashlytics-build.properties',
    ],
  },
  {
    id: 'unreal',
    name: 'Unreal',
    category: 'Frameworks',
    rules: [
      'Binaries/',
      'DerivedDataCache/',
      'Intermediate/',
      'Saved/',
      '.vs/',
      '*.opensdf',
      '*.sdf',
      '*.sln',
      '*.suo',
      '*.xcodeproj',
      '*.xcworkspace',
    ],
  },
  {
    id: 'android',
    name: 'Android',
    category: 'Frameworks',
    rules: [
      '*.apk',
      '*.aab',
      '*.ap_',
      '*.dex',
      '*.class',
      'bin/',
      'gen/',
      'out/',
      '.gradle/',
      'build/',
      'local.properties',
      'captures/',
      '.externalNativeBuild/',
      '.cxx/',
      '*.jks',
      '*.keystore',
    ],
  },
  {
    id: 'ios-xcode',
    name: 'iOS/Xcode',
    category: 'Frameworks',
    rules: [
      'build/',
      'DerivedData/',
      '*.moved-aside',
      '*.pbxuser',
      '*.mode1v3',
      '*.mode2v3',
      '*.perspectivev3',
      'xcuserdata/',
      '*.xcscmblueprint',
      '*.xccheckout',
      'Pods/',
      '*.hmap',
      '*.ipa',
      '*.xcarchive',
    ],
  },
  {
    id: 'terraform',
    name: 'Terraform',
    category: 'Frameworks',
    rules: [
      '**/.terraform/*',
      '*.tfstate',
      '*.tfstate.*',
      'crash.log',
      'crash.*.log',
      '*.tfvars',
      '*.tfvars.json',
      'override.tf',
      'override.tf.json',
      '*_override.tf',
      '*_override.tf.json',
      '.terraformrc',
      'terraform.rc',
      '.terraform.lock.hcl',
    ],
  },
  {
    id: 'serverless',
    name: 'Serverless',
    category: 'Frameworks',
    rules: ['.serverless/', '.webpack/', '.dynamodb/', '.build/'],
  },
  {
    id: 'jupyter',
    name: 'Jupyter',
    category: 'Frameworks',
    rules: ['.ipynb_checkpoints/', '*/.ipynb_checkpoints/*', 'profile_default/', 'ipython_config.py'],
  },
];
