// .gitignore rules for programming languages. Tool-specific.
// Content is hand-written based on well-known github/gitignore patterns,
// kept accurate but concise (not the full upstream lists).

import type { GitignoreTemplate } from './types';

export const LANGUAGE_TEMPLATES: readonly GitignoreTemplate[] = [
  {
    id: 'node',
    name: 'Node',
    category: 'Languages',
    rules: [
      'logs',
      '*.log',
      'npm-debug.log*',
      'yarn-debug.log*',
      'yarn-error.log*',
      'pnpm-debug.log*',
      'lerna-debug.log*',
      'node_modules/',
      'dist/',
      'dist-ssr/',
      'build/',
      '.npm',
      '.eslintcache',
      '.node_repl_history',
      '*.tsbuildinfo',
      'coverage/',
      '.nyc_output',
    ],
  },
  {
    id: 'python',
    name: 'Python',
    category: 'Languages',
    rules: [
      '__pycache__/',
      '*.py[cod]',
      '*$py.class',
      '*.so',
      'build/',
      'develop-eggs/',
      'dist/',
      'downloads/',
      'eggs/',
      '.eggs/',
      'lib/',
      'lib64/',
      'parts/',
      'sdist/',
      'var/',
      'wheels/',
      '*.egg-info/',
      '*.egg',
      'MANIFEST',
      'pip-log.txt',
      'pip-delete-this-directory.txt',
      'htmlcov/',
      '.tox/',
      '.nox/',
      '.coverage',
      '.coverage.*',
      '.cache',
      'nosetests.xml',
      'coverage.xml',
      '*.cover',
      '.hypothesis/',
      '.pytest_cache/',
      '*.mo',
      '*.pot',
      'instance/',
      '.scrapy',
      'docs/_build/',
      '.ipynb_checkpoints',
      'profile_default/',
      'ipython_config.py',
      '.python-version',
      '__pypackages__/',
      'celerybeat-schedule',
      'celerybeat.pid',
      '.venv',
      'env/',
      'venv/',
      'ENV/',
      '.spyderproject',
      '.spyproject',
      '.ropeproject',
      '.mypy_cache/',
      '.dmypy.json',
      'dmypy.json',
      '.pyre/',
      '.pytype/',
      'cython_debug/',
    ],
  },
  {
    id: 'java',
    name: 'Java',
    category: 'Languages',
    rules: [
      '*.class',
      '*.ctxt',
      '.mtj.tmp/',
      '*.jar',
      '*.war',
      '*.nar',
      '*.ear',
      'hs_err_pid*',
      'replay_pid*',
      'target/',
      '.classpath',
      '.project',
      '.settings/',
      'bin/',
    ],
  },
  {
    id: 'go',
    name: 'Go',
    category: 'Languages',
    rules: [
      '*.exe',
      '*.exe~',
      '*.dll',
      '*.so',
      '*.dylib',
      '*.test',
      '*.out',
      'go.work',
      'go.work.sum',
      'vendor/',
      '/bin/',
    ],
  },
  {
    id: 'rust',
    name: 'Rust',
    category: 'Languages',
    rules: ['/target/', '**/*.rs.bk', '*.pdb'],
  },
  {
    id: 'cpp',
    name: 'C/C++',
    category: 'Languages',
    rules: [
      '*.o',
      '*.obj',
      '*.elf',
      '*.exe',
      '*.out',
      '*.a',
      '*.lib',
      '*.so',
      '*.so.*',
      '*.dylib',
      '*.dll',
      '*.i',
      '*.ii',
      '*.gch',
      '*.pch',
      '*.dSYM/',
      '*.su',
      '*.idb',
      '*.pdb',
      'CMakeFiles/',
      'CMakeCache.txt',
      'cmake_install.cmake',
      'build/',
    ],
  },
  {
    id: 'csharp',
    name: 'C#/.NET',
    category: 'Languages',
    rules: [
      'bin/',
      'obj/',
      '*.user',
      '*.suo',
      '*.userosscache',
      '*.sln.docstates',
      '[Dd]ebug/',
      '[Rr]elease/',
      'x64/',
      'x86/',
      '*.dll',
      '*.pdb',
      '*.cache',
      '.vs/',
      '*.nupkg',
      'project.lock.json',
      'artifacts/',
      'TestResult.xml',
    ],
  },
  {
    id: 'php',
    name: 'PHP',
    category: 'Languages',
    rules: [
      'vendor/',
      'composer.phar',
      '.phpunit.result.cache',
      '.php_cs.cache',
      '.php-cs-fixer.cache',
      '*.log',
    ],
  },
  {
    id: 'ruby',
    name: 'Ruby',
    category: 'Languages',
    rules: [
      '*.gem',
      '*.rbc',
      '/.config',
      '/coverage/',
      '/InstalledFiles',
      '/pkg/',
      '/spec/reports/',
      '/spec/examples.txt',
      '/test/tmp/',
      '/test/version_tmp/',
      '/tmp/',
      '.bundle/',
      'vendor/bundle',
      'log/*.log',
      '.byebug_history',
      '.rvmrc',
      '.rspec_status',
    ],
  },
  {
    id: 'swift',
    name: 'Swift',
    category: 'Languages',
    rules: [
      '.build/',
      '.swiftpm/',
      'DerivedData/',
      '*.moved-aside',
      'Package.resolved',
      '*.xcodeproj',
    ],
  },
  {
    id: 'kotlin',
    name: 'Kotlin',
    category: 'Languages',
    rules: [
      '*.class',
      '.gradle/',
      'build/',
      'out/',
      '*.kotlin_module',
      '.kotlin/',
      'local.properties',
    ],
  },
  {
    id: 'dart',
    name: 'Dart/Flutter',
    category: 'Languages',
    rules: [
      '.dart_tool/',
      '.packages',
      '.pub-cache/',
      '.pub/',
      'build/',
      '*.g.dart',
      '*.freezed.dart',
      '.flutter-plugins',
      '.flutter-plugins-dependencies',
      '.metadata',
      'ios/Flutter/Generated.xcconfig',
      'ios/Flutter/flutter_export_environment.sh',
      'android/local.properties',
      '*.iml',
    ],
  },
  {
    id: 'elixir',
    name: 'Elixir',
    category: 'Languages',
    rules: [
      '/_build/',
      '/cover/',
      '/deps/',
      '/doc/',
      '/.fetch',
      'erl_crash.dump',
      '*.ez',
      '*.beam',
      '/config/*.secret.exs',
      '.elixir_ls/',
    ],
  },
  {
    id: 'scala',
    name: 'Scala',
    category: 'Languages',
    rules: [
      '*.class',
      '*.log',
      'target/',
      '.bloop/',
      '.metals/',
      '.bsp/',
      'project/project/',
      'project/target/',
    ],
  },
  {
    id: 'r',
    name: 'R',
    category: 'Languages',
    rules: [
      '.Rproj.user/',
      '.Rhistory',
      '.RData',
      '.Ruserdata',
      '*.Rout',
      '.Rprofile',
      'packrat/',
      'renv/library/',
      'renv/staging/',
      '*.rdb',
      '*.rdx',
    ],
  },
];
